window.AVARIAS_SEED = {
  "generatedAt": "2026-05-10T12:14:26",
  "sourceFile": "Avarias Camiões.xlsx",
  "options": {
    "statuses": [
      "Parado",
      "Aguarda entrada na oficina",
      "Pode circular",
      "Aguarda pecas",
      "Agendado",
      "Concluido"
    ],
    "types": [
      "Motor",
      "Transmissao",
      "Travoes",
      "Eletrica",
      "Suspensao",
      "Pneus",
      "Hidraulico",
      "Carroceria",
      "Climatizacao",
      "Revisao",
      "Outro"
    ],
    "workshopTypes": [
      "Interna",
      "Externa"
    ],
    "fleetStatuses": [
      "Ativa",
      "Manutencao preventiva",
      "Vendida",
      "Abatida",
      "Cedida",
      "Inativa",
      "Alugada"
    ]
  },
  "fleet": [
    {
      "equipment": 815,
      "plate": "L-170277",
      "description": "Cisterna descarga lateral",
      "brand": "Hermanns S AL 2C",
      "model": "",
      "year": 2004,
      "status": "Ativa",
      "fleetEntryAt": "2004-01-22",
      "fleetExitAt": null,
      "exitReason": "",
      "notes": ""
    },
    {
      "equipment": 818,
      "plate": "L-174917",
      "description": "Cisterna descarga lateral",
      "brand": "Hermanns S AL 2C",
      "model": "",
      "year": 2005,
      "status": "Ativa",
      "fleetEntryAt": "2005-01-11",
      "fleetExitAt": null,
      "exitReason": "",
      "notes": ""
    },
    {
      "equipment": 825,
      "plate": "L-183518",
      "description": "Cisterna descarga lateral",
      "brand": "Hermanns S AL 2C",
      "model": "",
      "year": 2007,
      "status": "Ativa",
      "fleetEntryAt": "2007-01-15",
      "fleetExitAt": null,
      "exitReason": "",
      "notes": ""
    },
    {
      "equipment": 829,
      "plate": "SE-886",
      "description": "Cisterna descarga lateral",
      "brand": "Hermanns S AL 2C",
      "model": "",
      "year": 2008,
      "status": "Ativa",
      "fleetEntryAt": "2008-02-07",
      "fleetExitAt": null,
      "exitReason": "",
      "notes": ""
    },
    {
      "equipment": 830,
      "plate": "SE-906",
      "description": "Cisterna descarga lateral",
      "brand": "Hermanns S AL 2C",
      "model": "",
      "year": 2008,
      "status": "Ativa",
      "fleetEntryAt": "2008-02-19",
      "fleetExitAt": null,
      "exitReason": "",
      "notes": ""
    },
    {
      "equipment": 832,
      "plate": "SE-916",
      "description": "Cisterna descarga lateral",
      "brand": "Hermanns S AL 2C",
      "model": "",
      "year": 2008,
      "status": "Ativa",
      "fleetEntryAt": "2008-02-29",
      "fleetExitAt": null,
      "exitReason": "",
      "notes": ""
    },
    {
      "equipment": 834,
      "plate": "SE-992",
      "description": "Cisterna descarga lateral",
      "brand": "Hermanns S AL 2C 31 T",
      "model": null,
      "year": 2008,
      "status": "Ativa",
      "fleetEntryAt": "2008-04-07",
      "fleetExitAt": null,
      "exitReason": "",
      "notes": ""
    },
    {
      "equipment": 836,
      "plate": "SE-1144",
      "description": "Cisterna descarga lateral",
      "brand": "Omeps S 122",
      "model": "",
      "year": 2008,
      "status": "Ativa",
      "fleetEntryAt": "2008-06-19",
      "fleetExitAt": null,
      "exitReason": "",
      "notes": ""
    },
    {
      "equipment": 839,
      "plate": "SE-1347",
      "description": "Cisterna descarga lateral",
      "brand": "Hermanns S AL 2C",
      "model": "",
      "year": 2008,
      "status": "Ativa",
      "fleetEntryAt": "2008-09-26",
      "fleetExitAt": null,
      "exitReason": "",
      "notes": ""
    },
    {
      "equipment": 841,
      "plate": "SE-1349",
      "description": "Cisterna descarga lateral",
      "brand": "Hermanns S AL 2C",
      "model": "",
      "year": 2008,
      "status": "Ativa",
      "fleetEntryAt": "2008-09-26",
      "fleetExitAt": null,
      "exitReason": "",
      "notes": ""
    },
    {
      "equipment": 844,
      "plate": "P-81998",
      "description": "Porta-Silos",
      "brand": "Leciñena 2E-RD P Silos",
      "model": null,
      "year": null,
      "status": "Ativa",
      "fleetEntryAt": null,
      "fleetExitAt": null,
      "exitReason": "",
      "notes": ""
    },
    {
      "equipment": 845,
      "plate": "SE-2067",
      "description": "Cisterna Basculante",
      "brand": "Hermanns SALB 42 (H-S3E/SM)",
      "model": null,
      "year": 2010,
      "status": "Ativa",
      "fleetEntryAt": "2010-01-07",
      "fleetExitAt": null,
      "exitReason": "",
      "notes": ""
    },
    {
      "equipment": 848,
      "plate": "L-188051",
      "description": "Semi-reboque Caixa",
      "brand": "Invepe BAS 8 AL",
      "model": "",
      "year": 2008,
      "status": "Ativa",
      "fleetEntryAt": "2008-05-12",
      "fleetExitAt": null,
      "exitReason": "",
      "notes": ""
    },
    {
      "equipment": 849,
      "plate": "L-188158",
      "description": "Semi-reboque Caixa",
      "brand": "Invepe BAS 8 AL",
      "model": "",
      "year": 2008,
      "status": "Ativa",
      "fleetEntryAt": "2008-05-21",
      "fleetExitAt": null,
      "exitReason": "",
      "notes": ""
    },
    {
      "equipment": 852,
      "plate": "74-TC-55",
      "description": "Camião",
      "brand": "Volvo T FH (4X2)",
      "model": "",
      "year": 2017,
      "status": "Ativa",
      "fleetEntryAt": "2017-06-07",
      "fleetExitAt": null,
      "exitReason": "",
      "notes": ""
    },
    {
      "equipment": 854,
      "plate": "LE-2306",
      "description": "Cisterna Basculante",
      "brand": "Kassbohrer K.SSK40",
      "model": null,
      "year": 2017,
      "status": "Ativa",
      "fleetEntryAt": "2017-09-19",
      "fleetExitAt": null,
      "exitReason": "",
      "notes": ""
    },
    {
      "equipment": 855,
      "plate": "LE-3158",
      "description": "Cisterna Basculantes",
      "brand": "Kassbohrer K.SSK40",
      "model": null,
      "year": 2019,
      "status": "Ativa",
      "fleetEntryAt": "2019-01-10",
      "fleetExitAt": null,
      "exitReason": "",
      "notes": ""
    },
    {
      "equipment": 856,
      "plate": "25-ZO-43",
      "description": "Camião",
      "brand": "Volvo T FH (4X2)",
      "model": "",
      "year": 2019,
      "status": "Ativa",
      "fleetEntryAt": "2019-12-03",
      "fleetExitAt": null,
      "exitReason": "",
      "notes": ""
    },
    {
      "equipment": 857,
      "plate": "25-ZO-46",
      "description": "Camião",
      "brand": "Volvo T FH (4X2)",
      "model": "",
      "year": 2019,
      "status": "Ativa",
      "fleetEntryAt": "2019-12-03",
      "fleetExitAt": null,
      "exitReason": "",
      "notes": ""
    },
    {
      "equipment": 858,
      "plate": "75-ZS-76",
      "description": "Camião",
      "brand": "MAN TGX 18.510 4x2",
      "model": null,
      "year": 2020,
      "status": "Ativa",
      "fleetEntryAt": "2020-01-16",
      "fleetExitAt": null,
      "exitReason": "",
      "notes": ""
    },
    {
      "equipment": 859,
      "plate": "75-ZS-77",
      "description": "Camião",
      "brand": "MAN TGX 18.510 4x2",
      "model": null,
      "year": 2020,
      "status": "Ativa",
      "fleetEntryAt": "2020-01-16",
      "fleetExitAt": null,
      "exitReason": "",
      "notes": ""
    },
    {
      "equipment": 860,
      "plate": "L-198570",
      "description": "Semi-reboque Caixa",
      "brand": "Invepe SR3",
      "model": "",
      "year": 2015,
      "status": "Ativa",
      "fleetEntryAt": "2015-09-24",
      "fleetExitAt": null,
      "exitReason": "",
      "notes": ""
    },
    {
      "equipment": 861,
      "plate": "L-209373",
      "description": "Semi-reboque Caixa",
      "brand": "Galucho SGB3",
      "model": "",
      "year": 2021,
      "status": "Ativa",
      "fleetEntryAt": "2021-04-05",
      "fleetExitAt": null,
      "exitReason": "",
      "notes": ""
    },
    {
      "equipment": 862,
      "plate": "L-209374",
      "description": "Semi-reboque Caixa",
      "brand": "Galucho SGB3",
      "model": "",
      "year": 2021,
      "status": "Ativa",
      "fleetEntryAt": "2021-04-05",
      "fleetExitAt": null,
      "exitReason": "",
      "notes": ""
    },
    {
      "equipment": 863,
      "plate": "L-209375",
      "description": "Semi-reboque Caixa",
      "brand": "Galucho SGB3",
      "model": "",
      "year": 2021,
      "status": "Ativa",
      "fleetEntryAt": "2021-04-05",
      "fleetExitAt": null,
      "exitReason": "",
      "notes": ""
    },
    {
      "equipment": 864,
      "plate": "AJ48BP",
      "description": "Camião",
      "brand": "MAN TGS 18.430 4x2",
      "model": null,
      "year": 2021,
      "status": "Ativa",
      "fleetEntryAt": "2021-08-24",
      "fleetExitAt": null,
      "exitReason": "",
      "notes": ""
    },
    {
      "equipment": 865,
      "plate": "AJ49BP",
      "description": "Camião",
      "brand": "MAN TGS 18.430 4x2",
      "model": null,
      "year": 2021,
      "status": "Ativa",
      "fleetEntryAt": "2021-08-24",
      "fleetExitAt": null,
      "exitReason": "",
      "notes": ""
    },
    {
      "equipment": 866,
      "plate": "AJ50BP",
      "description": "Camião",
      "brand": "MAN TGS 18.430 4x2",
      "model": null,
      "year": 2021,
      "status": "Ativa",
      "fleetEntryAt": "2021-08-24",
      "fleetExitAt": null,
      "exitReason": "",
      "notes": ""
    },
    {
      "equipment": 867,
      "plate": "AJ50GD",
      "description": "Camião",
      "brand": "MAN TGS 18.430 4x2",
      "model": null,
      "year": 2021,
      "status": "Ativa",
      "fleetEntryAt": "2021-09-06",
      "fleetExitAt": null,
      "exitReason": "",
      "notes": ""
    },
    {
      "equipment": 868,
      "plate": "AJ15MG",
      "description": "Camião",
      "brand": "MAN TGS 18.430 4x2",
      "model": null,
      "year": 2021,
      "status": "Ativa",
      "fleetEntryAt": "2021-09-22",
      "fleetExitAt": null,
      "exitReason": "",
      "notes": ""
    },
    {
      "equipment": 870,
      "plate": "L-183985",
      "description": "Semi-reboque Caixa",
      "brand": "MONTENEGRO SVF-2G-18AE",
      "model": null,
      "year": 2007,
      "status": "Ativa",
      "fleetEntryAt": "2007-03-01",
      "fleetExitAt": null,
      "exitReason": "",
      "notes": ""
    },
    {
      "equipment": 871,
      "plate": "L-183988",
      "description": "Semi-reboque Caixa",
      "brand": "MONTENEGRO SVF-2G-18AE",
      "model": null,
      "year": 2007,
      "status": "Ativa",
      "fleetEntryAt": "2007-03-01",
      "fleetExitAt": null,
      "exitReason": "",
      "notes": ""
    },
    {
      "equipment": 873,
      "plate": "L-159175",
      "description": "Semi-reboque Caixa",
      "brand": "Basben SB20SM",
      "model": "",
      "year": 2002,
      "status": "Ativa",
      "fleetEntryAt": "2002-05-16",
      "fleetExitAt": null,
      "exitReason": "",
      "notes": ""
    },
    {
      "equipment": 875,
      "plate": "L-37858",
      "description": "Estrado",
      "brand": "MATALOFABRIL SR2-25500/YT/7165",
      "model": null,
      "year": 1976,
      "status": "Ativa",
      "fleetEntryAt": "1976-09-08",
      "fleetExitAt": null,
      "exitReason": "",
      "notes": ""
    },
    {
      "equipment": 876,
      "plate": "L-155299",
      "description": "Estrado",
      "brand": "Montenegro SPL 3S 13.62",
      "model": null,
      "year": 1998,
      "status": "Ativa",
      "fleetEntryAt": "1998-10-27",
      "fleetExitAt": null,
      "exitReason": "",
      "notes": ""
    },
    {
      "equipment": 877,
      "plate": "L-137878",
      "description": "Porta Máquinas",
      "brand": "CARSUL SRR-12,0-PM-BED-31,4",
      "model": null,
      "year": 1998,
      "status": "Ativa",
      "fleetEntryAt": "1998-02-19",
      "fleetExitAt": null,
      "exitReason": "",
      "notes": ""
    },
    {
      "equipment": 880,
      "plate": "L-210306",
      "description": "Semi-reboque Caixa",
      "brand": "Galucho SGB3",
      "model": "",
      "year": 2021,
      "status": "Ativa",
      "fleetEntryAt": "2021-08-13",
      "fleetExitAt": null,
      "exitReason": "",
      "notes": ""
    },
    {
      "equipment": 881,
      "plate": "AT05RJ",
      "description": "Camião",
      "brand": "MAN TGX 18.510 4x2",
      "model": null,
      "year": 2022,
      "status": "Ativa",
      "fleetEntryAt": "2022-10-11",
      "fleetExitAt": null,
      "exitReason": "",
      "notes": ""
    },
    {
      "equipment": 882,
      "plate": "AT06RJ",
      "description": "Camião",
      "brand": "MAN TGX 18.510 4x2",
      "model": null,
      "year": 2022,
      "status": "Ativa",
      "fleetEntryAt": "2022-10-11",
      "fleetExitAt": null,
      "exitReason": "",
      "notes": ""
    },
    {
      "equipment": 883,
      "plate": "AT07RJ",
      "description": "Camião",
      "brand": "MAN TGX 18.510 4x2",
      "model": null,
      "year": 2022,
      "status": "Ativa",
      "fleetEntryAt": "2022-10-11",
      "fleetExitAt": null,
      "exitReason": "",
      "notes": ""
    },
    {
      "equipment": 884,
      "plate": "AT08RJ",
      "description": "Camião",
      "brand": "MAN TGX 18.510 4x2",
      "model": null,
      "year": 2022,
      "status": "Ativa",
      "fleetEntryAt": "2022-10-11",
      "fleetExitAt": null,
      "exitReason": "",
      "notes": ""
    },
    {
      "equipment": 885,
      "plate": "AT54JF",
      "description": "Camião",
      "brand": "MAN TGX 18.510 4x2",
      "model": null,
      "year": 2022,
      "status": "Ativa",
      "fleetEntryAt": "2022-09-26",
      "fleetExitAt": null,
      "exitReason": "",
      "notes": ""
    },
    {
      "equipment": 886,
      "plate": "AT55JF",
      "description": "Camião",
      "brand": "MAN TGX 18.510 4x2",
      "model": null,
      "year": 2022,
      "status": "Ativa",
      "fleetEntryAt": "2022-09-26",
      "fleetExitAt": null,
      "exitReason": "",
      "notes": ""
    },
    {
      "equipment": 887,
      "plate": "AT57JF",
      "description": "Camião",
      "brand": "MAN TGX 18.510 4x2",
      "model": null,
      "year": 2022,
      "status": "Ativa",
      "fleetEntryAt": "2022-09-26",
      "fleetExitAt": null,
      "exitReason": "",
      "notes": ""
    },
    {
      "equipment": 888,
      "plate": "AT59JF",
      "description": "Camião",
      "brand": "MAN TGX 18.510 4x2",
      "model": null,
      "year": 2022,
      "status": "Ativa",
      "fleetEntryAt": "2022-09-26",
      "fleetExitAt": null,
      "exitReason": "",
      "notes": ""
    },
    {
      "equipment": 889,
      "plate": "AT60JF",
      "description": "Camião",
      "brand": "MAN TGX 18.510 4x2",
      "model": null,
      "year": 2022,
      "status": "Ativa",
      "fleetEntryAt": "2022-09-26",
      "fleetExitAt": null,
      "exitReason": "",
      "notes": ""
    },
    {
      "equipment": 890,
      "plate": "AU01EM",
      "description": "Camião",
      "brand": "MAN TGX 18.510 4x2",
      "model": null,
      "year": 2022,
      "status": "Ativa",
      "fleetEntryAt": "2022-10-31",
      "fleetExitAt": null,
      "exitReason": "",
      "notes": ""
    },
    {
      "equipment": 891,
      "plate": "BA61UH",
      "description": "Camião",
      "brand": "MAN TGS 18.470 4x2 BL SA",
      "model": null,
      "year": 2023,
      "status": "Ativa",
      "fleetEntryAt": "2023-05-15",
      "fleetExitAt": null,
      "exitReason": "",
      "notes": ""
    },
    {
      "equipment": 892,
      "plate": "BB06OD",
      "description": "Camião",
      "brand": "MAN TGS 18.430 4x2",
      "model": null,
      "year": 2023,
      "status": "Ativa",
      "fleetEntryAt": "2023-06-12",
      "fleetExitAt": null,
      "exitReason": "",
      "notes": ""
    },
    {
      "equipment": 893,
      "plate": "BD87AZ",
      "description": "Camião",
      "brand": "MAN TGS 18.430 4x2",
      "model": null,
      "year": 2023,
      "status": "Ativa",
      "fleetEntryAt": "2023-08-09",
      "fleetExitAt": null,
      "exitReason": "",
      "notes": ""
    },
    {
      "equipment": 894,
      "plate": "L-183989",
      "description": "Semi-reboque Caixa",
      "brand": "MONTENEGRO SVF-2G-18AE",
      "model": null,
      "year": 2007,
      "status": "Ativa",
      "fleetEntryAt": "2007-03-01",
      "fleetExitAt": null,
      "exitReason": "",
      "notes": ""
    },
    {
      "equipment": 895,
      "plate": "BC68VO",
      "description": "Autocarro",
      "brand": "Temsa Prestij SX",
      "model": "",
      "year": 2023,
      "status": "Ativa",
      "fleetEntryAt": "2023-07-31",
      "fleetExitAt": null,
      "exitReason": "",
      "notes": ""
    },
    {
      "equipment": 896,
      "plate": "L-198571",
      "description": "Semi-reboque Caixa",
      "brand": "Invepe SR3",
      "model": "",
      "year": 2015,
      "status": "Ativa",
      "fleetEntryAt": "2015-09-24",
      "fleetExitAt": null,
      "exitReason": "",
      "notes": ""
    },
    {
      "equipment": 5103,
      "plate": "L-146101",
      "description": "SVF 2G 18SE",
      "brand": "Montenegro",
      "model": "",
      "year": 1999,
      "status": "Ativa",
      "fleetEntryAt": "1999-06-29",
      "fleetExitAt": null,
      "exitReason": "",
      "notes": ""
    },
    {
      "equipment": 5104,
      "plate": "39-70-OE",
      "description": "Camião Rígido Cola",
      "brand": "Mercedes Ategos 26.28 B",
      "model": null,
      "year": 1999,
      "status": "Ativa",
      "fleetEntryAt": "1999-09-27",
      "fleetExitAt": null,
      "exitReason": "",
      "notes": ""
    },
    {
      "equipment": 5106,
      "plate": "28-58-OJ",
      "description": "Camião Rígido Caixa",
      "brand": "Volvo FL10",
      "model": "",
      "year": 1999,
      "status": "Ativa",
      "fleetEntryAt": "1999-10-22",
      "fleetExitAt": null,
      "exitReason": "",
      "notes": ""
    },
    {
      "equipment": 5109,
      "plate": "12-92-OR",
      "description": "Camião Rígido Água",
      "brand": "Mercedes Ategos 26.28 B (6x2)",
      "model": null,
      "year": 1999,
      "status": "Ativa",
      "fleetEntryAt": "1999-12-21",
      "fleetExitAt": null,
      "exitReason": "",
      "notes": ""
    },
    {
      "equipment": 5115,
      "plate": "L-154494",
      "description": "Porta-Máquinas",
      "brand": "Kaiser S530 3F",
      "model": "",
      "year": 2000,
      "status": "Ativa",
      "fleetEntryAt": "2000-12-18",
      "fleetExitAt": null,
      "exitReason": "",
      "notes": ""
    },
    {
      "equipment": 5122,
      "plate": "13-96-QP",
      "description": "Camião Rígido Cola",
      "brand": "Volvo FL 10",
      "model": "",
      "year": 2000,
      "status": "Ativa",
      "fleetEntryAt": "2000-11-15",
      "fleetExitAt": null,
      "exitReason": "",
      "notes": ""
    },
    {
      "equipment": 5173,
      "plate": "77-56-AB",
      "description": "Camião Rígido Água",
      "brand": "Mercedes 26.29 K/38",
      "model": null,
      "year": 1992,
      "status": "Ativa",
      "fleetEntryAt": "1992-03-19",
      "fleetExitAt": null,
      "exitReason": "",
      "notes": ""
    },
    {
      "equipment": 5194,
      "plate": "24-FA-85",
      "description": "Camião Rígido",
      "brand": "Volvo FM9 (6x4)",
      "model": "",
      "year": 2007,
      "status": "Ativa",
      "fleetEntryAt": "2007-12-28",
      "fleetExitAt": null,
      "exitReason": "",
      "notes": ""
    },
    {
      "equipment": 5195,
      "plate": "24-FA-86",
      "description": "Camião Rígido",
      "brand": "Volvo FM9 (6x4)",
      "model": "",
      "year": 2007,
      "status": "Ativa",
      "fleetEntryAt": "2007-12-28",
      "fleetExitAt": null,
      "exitReason": "",
      "notes": ""
    },
    {
      "equipment": 5196,
      "plate": "24-FA-87",
      "description": "Camião Rígido",
      "brand": "Volvo FM9 (6x4)",
      "model": "",
      "year": 2007,
      "status": "Ativa",
      "fleetEntryAt": "2007-12-28",
      "fleetExitAt": null,
      "exitReason": "",
      "notes": ""
    },
    {
      "equipment": 5197,
      "plate": "24-FA-88",
      "description": "Camião Rígido",
      "brand": "Volvo FM9 (6x4)",
      "model": "",
      "year": 2007,
      "status": "Ativa",
      "fleetEntryAt": "2007-12-25",
      "fleetExitAt": null,
      "exitReason": "",
      "notes": ""
    },
    {
      "equipment": 5204,
      "plate": "SE-1082",
      "description": "Porta-Máquinas",
      "brand": "A.R.B. SPM 3D/8.95",
      "model": null,
      "year": 2008,
      "status": "Ativa",
      "fleetEntryAt": "2008-05-12",
      "fleetExitAt": null,
      "exitReason": "",
      "notes": ""
    },
    {
      "equipment": 5205,
      "plate": "42-FF-74",
      "description": "Camião Rígido",
      "brand": "Volvo FM 13 (8x4)",
      "model": "",
      "year": 2008,
      "status": "Ativa",
      "fleetEntryAt": "2008-02-15",
      "fleetExitAt": null,
      "exitReason": "",
      "notes": ""
    },
    {
      "equipment": 5206,
      "plate": "42-FF-75",
      "description": "Camião Rígido",
      "brand": "Volvo FM 13 (8x4)",
      "model": "",
      "year": 2008,
      "status": "Ativa",
      "fleetEntryAt": "2008-02-15",
      "fleetExitAt": null,
      "exitReason": "",
      "notes": ""
    },
    {
      "equipment": 5211,
      "plate": "15-95-PE",
      "description": "Camião Rígido Cola",
      "brand": "Volvo FM 7 (6x4)",
      "model": "",
      "year": 2000,
      "status": "Ativa",
      "fleetEntryAt": "2000-03-10",
      "fleetExitAt": null,
      "exitReason": "",
      "notes": ""
    },
    {
      "equipment": 5245,
      "plate": "19-FT-63",
      "description": "Camião Rígido Cola",
      "brand": "Iveco Eurocargo 220",
      "model": null,
      "year": 2008,
      "status": "Ativa",
      "fleetEntryAt": "2008-05-21",
      "fleetExitAt": null,
      "exitReason": "",
      "notes": ""
    },
    {
      "equipment": 5254,
      "plate": "L-130016",
      "description": "Reboque Estrado",
      "brand": "FRUEAUF EPB",
      "model": "",
      "year": 1996,
      "status": "Ativa",
      "fleetEntryAt": "1996-06-04",
      "fleetExitAt": null,
      "exitReason": "",
      "notes": ""
    },
    {
      "equipment": 5258,
      "plate": "44-QI-50",
      "description": "Camião",
      "brand": "Volvo T FH-38 (4x2)",
      "model": null,
      "year": 2015,
      "status": "Ativa",
      "fleetEntryAt": "2015-09-14",
      "fleetExitAt": null,
      "exitReason": "",
      "notes": ""
    },
    {
      "equipment": 5259,
      "plate": "44-QI-51",
      "description": "Camião",
      "brand": "Volvo T FH-38 (4x2)",
      "model": null,
      "year": 2015,
      "status": "Ativa",
      "fleetEntryAt": "2015-09-14",
      "fleetExitAt": null,
      "exitReason": "",
      "notes": ""
    },
    {
      "equipment": 5269,
      "plate": "94-TA-46",
      "description": "Camião",
      "brand": "Volvo T FH540 (6x4)",
      "model": null,
      "year": 2017,
      "status": "Ativa",
      "fleetEntryAt": "2017-05-29",
      "fleetExitAt": null,
      "exitReason": "",
      "notes": ""
    },
    {
      "equipment": 5270,
      "plate": "AV-55672",
      "description": "Porta-Máquinas",
      "brand": "Invepe RPM 133",
      "model": "",
      "year": 2017,
      "status": "Ativa",
      "fleetEntryAt": "2017-05-19",
      "fleetExitAt": null,
      "exitReason": "",
      "notes": ""
    },
    {
      "equipment": 5276,
      "plate": "L-190357",
      "description": "Reboque Estrado XICO",
      "brand": "Joluso RR-2D-6,5",
      "model": "",
      "year": 2009,
      "status": "Ativa",
      "fleetEntryAt": "2009-06-06",
      "fleetExitAt": null,
      "exitReason": "",
      "notes": ""
    },
    {
      "equipment": 5295,
      "plate": "25-ZO-41",
      "description": "Camião",
      "brand": "Volvo FH (4) D13K (4x2)",
      "model": null,
      "year": 2019,
      "status": "Ativa",
      "fleetEntryAt": "2019-12-03",
      "fleetExitAt": null,
      "exitReason": "",
      "notes": ""
    },
    {
      "equipment": 5296,
      "plate": "25-ZO-49",
      "description": "Camião",
      "brand": "Volvo FH D13K (4x2)",
      "model": null,
      "year": 2019,
      "status": "Ativa",
      "fleetEntryAt": "2019-12-03",
      "fleetExitAt": null,
      "exitReason": "",
      "notes": ""
    },
    {
      "equipment": 5297,
      "plate": "25-ZO-44",
      "description": "Camião-Grua",
      "brand": "Volvo FMX 500 (8x4)",
      "model": null,
      "year": 2019,
      "status": "Ativa",
      "fleetEntryAt": "2019-12-03",
      "fleetExitAt": null,
      "exitReason": "",
      "notes": ""
    },
    {
      "equipment": 5298,
      "plate": "25-ZO-42",
      "description": "Camião Rígido",
      "brand": "Volvo FMX 460 (8x4)",
      "model": null,
      "year": 2019,
      "status": "Ativa",
      "fleetEntryAt": "2019-12-03",
      "fleetExitAt": null,
      "exitReason": "",
      "notes": ""
    },
    {
      "equipment": 5299,
      "plate": "25-ZO-51",
      "description": "Camião Rígido",
      "brand": "Volvo FMX 460 (8x4)",
      "model": null,
      "year": 2019,
      "status": "Ativa",
      "fleetEntryAt": "03/19/2019",
      "fleetExitAt": null,
      "exitReason": "",
      "notes": ""
    },
    {
      "equipment": 5302,
      "plate": "L-207077",
      "description": "Semi-Reboque Caixa",
      "brand": "Galucho SGB3",
      "model": "",
      "year": 2020,
      "status": "Ativa",
      "fleetEntryAt": "2020-01-30",
      "fleetExitAt": null,
      "exitReason": "",
      "notes": ""
    },
    {
      "equipment": 5303,
      "plate": "L-207078",
      "description": "Semi-Reboque Caixa",
      "brand": "Galucho SGB3",
      "model": "",
      "year": 2020,
      "status": "Ativa",
      "fleetEntryAt": "2020-01-30",
      "fleetExitAt": null,
      "exitReason": "",
      "notes": ""
    },
    {
      "equipment": 5316,
      "plate": "AD27MD",
      "description": "Camião-Grua",
      "brand": "Volvo FM 4 420 (6x4)",
      "model": null,
      "year": 2020,
      "status": "Ativa",
      "fleetEntryAt": "2020-10-27",
      "fleetExitAt": null,
      "exitReason": "",
      "notes": ""
    },
    {
      "equipment": 5323,
      "plate": "29-15-ZF",
      "description": "Camião Rígido Cola",
      "brand": "Volvo FM9 (4x2)",
      "model": "",
      "year": 2004,
      "status": "Ativa",
      "fleetEntryAt": "2004-11-26",
      "fleetExitAt": null,
      "exitReason": "",
      "notes": ""
    },
    {
      "equipment": 5330,
      "plate": "L-209506",
      "description": "Semi-Reboque Caixa",
      "brand": "Galucho SGB3",
      "model": "",
      "year": 2021,
      "status": "Ativa",
      "fleetEntryAt": "2021-04-26",
      "fleetExitAt": null,
      "exitReason": "",
      "notes": ""
    },
    {
      "equipment": 5331,
      "plate": "L-209507",
      "description": "Semi-Reboque Caixa",
      "brand": "Galucho SGB3",
      "model": "",
      "year": 2021,
      "status": "Ativa",
      "fleetEntryAt": "2021-04-26",
      "fleetExitAt": null,
      "exitReason": "",
      "notes": ""
    },
    {
      "equipment": 5337,
      "plate": "L-210305",
      "description": "Semi-reboque Caixa",
      "brand": "Galucho SGB3",
      "model": "",
      "year": 2021,
      "status": "Ativa",
      "fleetEntryAt": "2021-08-16",
      "fleetExitAt": null,
      "exitReason": "",
      "notes": ""
    },
    {
      "equipment": 5347,
      "plate": "AN87AV",
      "description": "Camião Rígido",
      "brand": "Volvo FMX 460 (8x4)",
      "model": null,
      "year": 2021,
      "status": "Ativa",
      "fleetEntryAt": "2021-12-22",
      "fleetExitAt": null,
      "exitReason": "",
      "notes": ""
    },
    {
      "equipment": 5348,
      "plate": "AN90AV",
      "description": "Camião Rígido",
      "brand": "Volvo FMX 460 (8x4)",
      "model": null,
      "year": 2021,
      "status": "Ativa",
      "fleetEntryAt": "2021-12-22",
      "fleetExitAt": null,
      "exitReason": "",
      "notes": ""
    },
    {
      "equipment": 5368,
      "plate": "57-74-PF",
      "description": "Camião Rígido Água",
      "brand": "Volvo FM 7 (6x4)",
      "model": "",
      "year": 2000,
      "status": "Ativa",
      "fleetEntryAt": "2000-03-20",
      "fleetExitAt": null,
      "exitReason": "",
      "notes": ""
    },
    {
      "equipment": 5378,
      "plate": "BE08MB",
      "description": "Camião",
      "brand": "Volvo FH500 (4) D13K (4X2)",
      "model": null,
      "year": 2023,
      "status": "Ativa",
      "fleetEntryAt": "2023-10-18",
      "fleetExitAt": null,
      "exitReason": "",
      "notes": ""
    },
    {
      "equipment": 5379,
      "plate": "BE09MB",
      "description": "Camião",
      "brand": "Volvo FH500 (4) D13K (4x2)",
      "model": null,
      "year": 2023,
      "status": "Ativa",
      "fleetEntryAt": "2023-10-18",
      "fleetExitAt": null,
      "exitReason": "",
      "notes": ""
    },
    {
      "equipment": 5380,
      "plate": "BE10MB",
      "description": "",
      "brand": "Volvo FH500 (4) D13K (4x2)",
      "model": null,
      "year": 2023,
      "status": "Ativa",
      "fleetEntryAt": "2023-10-18",
      "fleetExitAt": null,
      "exitReason": "",
      "notes": ""
    },
    {
      "equipment": 5381,
      "plate": "BE11MB",
      "description": "Camião",
      "brand": "Volvo FH500 (4) D13K (4x2)",
      "model": null,
      "year": 2023,
      "status": "Ativa",
      "fleetEntryAt": "2023-10-18",
      "fleetExitAt": null,
      "exitReason": "",
      "notes": ""
    },
    {
      "equipment": 40142,
      "plate": "L-219995",
      "description": "Semi-Reboque Caixa",
      "brand": "Galucho SGB3",
      "model": "",
      "year": 2025,
      "status": "Ativa",
      "fleetEntryAt": "2025-07-08",
      "fleetExitAt": null,
      "exitReason": "",
      "notes": ""
    },
    {
      "equipment": 40143,
      "plate": "L-219996",
      "description": "Semi-Reboque Caixa",
      "brand": "Galucho SGB3",
      "model": "",
      "year": 2025,
      "status": "Ativa",
      "fleetEntryAt": "2025-07-08",
      "fleetExitAt": null,
      "exitReason": "",
      "notes": ""
    },
    {
      "equipment": 40144,
      "plate": "L-219997",
      "description": "Semi-Reboque Caixa",
      "brand": "Galucho SGB3",
      "model": "",
      "year": 2025,
      "status": "Ativa",
      "fleetEntryAt": "2025-07-08",
      "fleetExitAt": null,
      "exitReason": "",
      "notes": ""
    },
    {
      "equipment": 40145,
      "plate": "L-219998",
      "description": "Semi-Reboque Caixa",
      "brand": "Galucho SGB 3",
      "model": "",
      "year": 2025,
      "status": "Ativa",
      "fleetEntryAt": "2025-07-08",
      "fleetExitAt": null,
      "exitReason": "",
      "notes": ""
    },
    {
      "equipment": 40146,
      "plate": "L-219999",
      "description": "Semi-Reboque Caixa",
      "brand": "Galucho SGB3",
      "model": "",
      "year": 2025,
      "status": "Ativa",
      "fleetEntryAt": "2025-07-08",
      "fleetExitAt": null,
      "exitReason": "",
      "notes": ""
    },
    {
      "equipment": 70021,
      "plate": "BG57ZE",
      "description": "Camião Rígido",
      "brand": "Volvo FMX 380 (6x4)",
      "model": null,
      "year": 2024,
      "status": "Ativa",
      "fleetEntryAt": "2024-02-06",
      "fleetExitAt": null,
      "exitReason": "",
      "notes": ""
    },
    {
      "equipment": 70022,
      "plate": "BG50ZE",
      "description": "Camião Rígido",
      "brand": "Volvo FMX 380 (6x4)",
      "model": null,
      "year": 2024,
      "status": "Ativa",
      "fleetEntryAt": "2024-02-06",
      "fleetExitAt": null,
      "exitReason": "",
      "notes": ""
    },
    {
      "equipment": 70023,
      "plate": "BG51ZE",
      "description": "Camião Rígido",
      "brand": "Volvo FMX 460 (8x4)",
      "model": null,
      "year": 2024,
      "status": "Ativa",
      "fleetEntryAt": "2024-03-02",
      "fleetExitAt": null,
      "exitReason": "",
      "notes": ""
    },
    {
      "equipment": 70024,
      "plate": "BG56ZE",
      "description": "Camião Rígido",
      "brand": "Volvo FMX 460 (8x4)",
      "model": null,
      "year": 2024,
      "status": "Ativa",
      "fleetEntryAt": "2024-02-06",
      "fleetExitAt": null,
      "exitReason": "",
      "notes": ""
    },
    {
      "equipment": 70025,
      "plate": "BG55ZE",
      "description": "Camião Rígido",
      "brand": "Volvo FMX 460 (8x4)",
      "model": null,
      "year": 2024,
      "status": "Ativa",
      "fleetEntryAt": "2024-02-06",
      "fleetExitAt": null,
      "exitReason": "",
      "notes": ""
    },
    {
      "equipment": 70026,
      "plate": "BG54ZE",
      "description": "Camião Rígido",
      "brand": "Volvo FMX 460 (8x4)",
      "model": null,
      "year": 2024,
      "status": "Ativa",
      "fleetEntryAt": "2024-02-06",
      "fleetExitAt": null,
      "exitReason": "",
      "notes": ""
    },
    {
      "equipment": 70027,
      "plate": "BG53ZE",
      "description": "Camião Rígido",
      "brand": "Volvo FMX 460 (8x4)",
      "model": null,
      "year": 2024,
      "status": "Ativa",
      "fleetEntryAt": "2024-02-06",
      "fleetExitAt": null,
      "exitReason": "",
      "notes": ""
    },
    {
      "equipment": 70028,
      "plate": "BH50VS",
      "description": "Camião-Grua",
      "brand": "Volvo FMX 500 (8x4)",
      "model": null,
      "year": 2024,
      "status": "Ativa",
      "fleetEntryAt": "2024-03-15",
      "fleetExitAt": null,
      "exitReason": "",
      "notes": ""
    },
    {
      "equipment": 70029,
      "plate": "L-215831",
      "description": "Semi-Reboque Caixa",
      "brand": "Galucho SGB3",
      "model": "",
      "year": 2024,
      "status": "Ativa",
      "fleetEntryAt": "2024-03-28",
      "fleetExitAt": null,
      "exitReason": "",
      "notes": ""
    },
    {
      "equipment": 70030,
      "plate": "BG52ZE",
      "description": "Camião",
      "brand": "Volvo T FH750 (6x4)",
      "model": null,
      "year": 2024,
      "status": "Ativa",
      "fleetEntryAt": "2024-02-06",
      "fleetExitAt": null,
      "exitReason": "",
      "notes": ""
    },
    {
      "equipment": 70035,
      "plate": "92-81-PA",
      "description": "Camião Rígido Água",
      "brand": "Volvo FM 7 (6x4)",
      "model": "",
      "year": 2000,
      "status": "Ativa",
      "fleetEntryAt": "2000-02-16",
      "fleetExitAt": null,
      "exitReason": "",
      "notes": ""
    },
    {
      "equipment": 70109,
      "plate": "L-215832",
      "description": "Semi-Reboque Caixa",
      "brand": "Galucho SGB3",
      "model": "",
      "year": 2024,
      "status": "Ativa",
      "fleetEntryAt": "2024-03-28",
      "fleetExitAt": null,
      "exitReason": "",
      "notes": ""
    },
    {
      "equipment": 70259,
      "plate": "74-TC-56",
      "description": "Camião",
      "brand": "T FH (4x2)",
      "model": "",
      "year": 2017,
      "status": "Ativa",
      "fleetEntryAt": "2017-06-07",
      "fleetExitAt": null,
      "exitReason": "",
      "notes": ""
    }
  ],
  "breakdowns": [
    {
      "id": "AV0104183507",
      "equipment": 5194,
      "plate": "24-FA-85",
      "type": "Suspensao",
      "status": "Concluido",
      "reportedAt": "2026-04-01",
      "workshopEntryAt": "2026-04-01",
      "expectedExitAt": "2026-04-02",
      "workshopType": "Interna",
      "workshop": "",
      "driver": "",
      "cost": null,
      "description": "Sistema de suspensão bastante danificado",
      "lastNote": "ok",
      "lastNoteAt": "2026-04-02",
      "historyNotes": "2026-04-01: Sistema de suspensão bastante danificado\n 2026-04-02: [Parado] 3 dias em oficina MAN\n 2026-04-02: [Parado] em oficina\n 2026-04-02: [Concluido] ok"
    },
    {
      "id": "AV0104183701",
      "equipment": 5206,
      "plate": "42-FF-75",
      "type": "Motor",
      "status": "Parado",
      "reportedAt": "2026-04-01",
      "workshopEntryAt": null,
      "expectedExitAt": null,
      "workshopType": "",
      "workshop": "",
      "driver": "",
      "cost": null,
      "description": "Carro deixa de acelarar passado 2 a 3 horas de trabalho com várias mensagens de erro",
      "lastNote": "travagem, ABS > 2-3 dias trabalho",
      "lastNoteAt": "2026-04-15",
      "historyNotes": "2026-04-01: Carro deixa de acelarar passado 2 a 3 horas de trabalho com várias mensagens de erro\n 2026-04-01: [Aguarda entrada na oficina] Terá de ir para oficina externa\n2026-04-15: [Parado] travagem, ABS > 2-3 dias trabalho"
    },
    {
      "id": "AV0104184056",
      "equipment": 5347,
      "plate": "AN87AV",
      "type": "Hidraulico",
      "status": "Concluido",
      "reportedAt": "2026-03-31",
      "workshopEntryAt": null,
      "expectedExitAt": "2026-04-14",
      "workshopType": "",
      "workshop": "",
      "driver": "",
      "cost": null,
      "description": "Está a verter óleo por um tubo de direção. Aguarda passagem de mecânico em obra",
      "lastNote": "ok",
      "lastNoteAt": "2026-04-14",
      "historyNotes": "2026-04-01: Está a verter óleo por um tubo de direção. Aguarda passagem de mecânico em obra\n2026-04-07: [Aguarda entrada na oficina] materiais já estão em oficina\n2026-04-14: [Concluido] ok"
    },
    {
      "id": "AV0104184252",
      "equipment": 5379,
      "plate": "BE09MB",
      "type": "Motor",
      "status": "Concluido",
      "reportedAt": "2026-03-27",
      "workshopEntryAt": "2026-03-31",
      "expectedExitAt": "2026-04-14",
      "workshopType": "Externa",
      "workshop": "MAN Lisboa",
      "driver": "",
      "cost": null,
      "description": "Redução de potencia a aguardar peças",
      "lastNote": "ok",
      "lastNoteAt": "2026-04-14",
      "historyNotes": "2026-04-01: Redução de potencia a aguardar peças\n 2026-04-02: [Parado] 2/04 e 06/04 previsão de ficar pronta\n2026-04-06: [Pode circular] Aguarda corte de corrente (fornecedor)\n2026-04-07: [Pode circular] material chega na 5ª feira 09/04/2026\n2026-04-14: [Concluido] ok"
    },
    {
      "id": "AV0104184512",
      "equipment": 5205,
      "plate": "42-FF-74",
      "type": "Hidraulico",
      "status": "Concluido",
      "reportedAt": "2026-04-01",
      "workshopEntryAt": null,
      "expectedExitAt": "2026-04-20",
      "workshopType": "",
      "workshop": "",
      "driver": "",
      "cost": null,
      "description": "Substituir oleo quando vier à oficina",
      "lastNote": "concluido",
      "lastNoteAt": "2026-04-20",
      "historyNotes": "2026-04-01: Substituir oleo quando vier à oficina\n2026-04-16: [Parado] 2º feira dia 20, estará pronta para trabalhar, se tudo correr bem\n2026-04-20: [Concluido] concluido"
    },
    {
      "id": "AV0104184721",
      "equipment": 5204,
      "plate": "SE-1082",
      "type": "Travoes",
      "status": "Concluido",
      "reportedAt": "2026-04-01",
      "workshopEntryAt": null,
      "expectedExitAt": "2026-04-14",
      "workshopType": "Interna",
      "workshop": "",
      "driver": "",
      "cost": null,
      "description": "Substituir calços",
      "lastNote": "ok",
      "lastNoteAt": "2026-04-14",
      "historyNotes": "2026-04-01: Substituir calços\n2026-04-14: [Concluido] ok"
    },
    {
      "id": "AV0104185028",
      "equipment": 865,
      "plate": "AJ49BP",
      "type": "Pneus",
      "status": "Concluido",
      "reportedAt": "2026-04-01",
      "workshopEntryAt": null,
      "expectedExitAt": null,
      "workshopType": "Interna",
      "workshop": "",
      "driver": "",
      "cost": null,
      "description": "Pneus Desiquilibrados, direção desalinhada, pressão dos pneus",
      "lastNote": "ok",
      "lastNoteAt": "2026-04-29",
      "historyNotes": "2026-04-01: Pneus Desiquilibrados, direção desalinhada, pressão dos pneus\n2026-04-06: [Agendado] Entrada Oficina Tojal 06/04\n2026-04-29: [Concluido] ok\n2026-04-29: [Concluido] ok\n2026-04-29: [Concluido] ok\n2026-04-29: [Concluido] ok"
    },
    {
      "id": "AV0104185058",
      "equipment": 865,
      "plate": "AJ49BP",
      "type": "Travoes",
      "status": "Concluido",
      "reportedAt": "2026-04-01",
      "workshopEntryAt": null,
      "expectedExitAt": null,
      "workshopType": "Interna",
      "workshop": "",
      "driver": "",
      "cost": null,
      "description": "Travagem irregular",
      "lastNote": "ok",
      "lastNoteAt": "2026-04-29",
      "historyNotes": "2026-04-01: Travagem irregular\n2026-04-06: [Agendado] Entrada Oficina Tojal 06/04\n2026-04-29: [Concluido] ok"
    },
    {
      "id": "AV0104185134",
      "equipment": 865,
      "plate": "AJ49BP",
      "type": "Travoes",
      "status": "Concluido",
      "reportedAt": "2026-04-01",
      "workshopEntryAt": null,
      "expectedExitAt": null,
      "workshopType": "Interna",
      "workshop": "",
      "driver": "",
      "cost": null,
      "description": "Problema ABS",
      "lastNote": "ok",
      "lastNoteAt": "2026-04-29",
      "historyNotes": "2026-04-01: Problema ABS\n2026-04-06: [Agendado] Entrada Oficina Tojal 06/04\n2026-04-29: [Concluido] ok"
    },
    {
      "id": "AV0104185206",
      "equipment": 865,
      "plate": "AJ49BP",
      "type": "Hidraulico",
      "status": "Concluido",
      "reportedAt": "2026-04-01",
      "workshopEntryAt": null,
      "expectedExitAt": "2026-04-16",
      "workshopType": "Interna",
      "workshop": "",
      "driver": "",
      "cost": null,
      "description": "Fuga de oleo pelos engates hidraulicos",
      "lastNote": "ok",
      "lastNoteAt": "2026-04-29",
      "historyNotes": "2026-04-01: Fuga de oleo pelos engates hidraulicos\n2026-04-14: [Parado] Fica pronto dia 14/04?\n2026-04-15: [Parado] supostamente ficará pronto para trabalhar dia 20/04\n2026-04-16: [Parado] Previsão é ficar pronta hoje 16/04\n2026-04-29: [Concluido] ok"
    },
    {
      "id": "AV0104185315",
      "equipment": 867,
      "plate": "AJ50GD",
      "type": "Travoes",
      "status": "Concluido",
      "reportedAt": "2026-04-01",
      "workshopEntryAt": null,
      "expectedExitAt": null,
      "workshopType": "Externa",
      "workshop": "",
      "driver": "",
      "cost": null,
      "description": "Travagem insuficiente, pressão de reserva",
      "lastNote": "ok",
      "lastNoteAt": "2026-04-14",
      "historyNotes": "2026-04-01: Travagem insuficiente, pressão de reserva\n2026-04-14: [Concluido] ok"
    },
    {
      "id": "AV0104190224",
      "equipment": 829,
      "plate": "SE-886",
      "type": "Outro",
      "status": "Concluido",
      "reportedAt": "2026-04-01",
      "workshopEntryAt": null,
      "expectedExitAt": null,
      "workshopType": "Externa",
      "workshop": "Cisterluso",
      "driver": "",
      "cost": null,
      "description": "Reparar tampas, colocar rolamentos novos no sistema de roscas, arranjar tampa da frente, arranjar a saia do cone da frente, para choque partido",
      "lastNote": "ok",
      "lastNoteAt": "2026-04-14",
      "historyNotes": "2026-04-01: Reparar tampas, colocar rolamentos novos no sistema de roscas, arranjar tampa da frente, arranjar a saia do cone da frente, para choque partido\n2026-04-14: [Concluido] ok"
    },
    {
      "id": "AV0104190342",
      "equipment": 893,
      "plate": "BD87AZ",
      "type": "Motor",
      "status": "Concluido",
      "reportedAt": "2026-04-01",
      "workshopEntryAt": null,
      "expectedExitAt": "2026-04-12",
      "workshopType": "Externa",
      "workshop": "MAN Turquel",
      "driver": "",
      "cost": null,
      "description": "Redução de potencia - Boia de Adblue (em Garantia)",
      "lastNote": "OK (em testes desde dia 12)",
      "lastNoteAt": "2026-04-14",
      "historyNotes": "2026-04-01: Redução de potencia - Boia de Adblue (em Garantia)\n2026-04-06: [Aguarda entrada na oficina] Entrada na MAN Turquel 06/04\n2026-04-07: [Pode circular] Viatura pronta para levantamento. 3 Semanas para testes com novo deposito de AD BLUE\n2026-04-14: [Concluido] OK (em testes desde dia 12)"
    },
    {
      "id": "AV0104190516",
      "equipment": 5194,
      "plate": "24-FA-85",
      "type": "Pneus",
      "status": "Concluido",
      "reportedAt": "2026-04-01",
      "workshopEntryAt": null,
      "expectedExitAt": null,
      "workshopType": "Interna",
      "workshop": "",
      "driver": "",
      "cost": null,
      "description": "Reparação de pneu (2º eixo direito interior)",
      "lastNote": "Reparação de pneu (2º eixo direito interior)",
      "lastNoteAt": "2026-04-01",
      "historyNotes": "2026-04-01: Reparação de pneu (2º eixo direito interior)"
    },
    {
      "id": "AV0104190700",
      "equipment": 5347,
      "plate": "AN87AV",
      "type": "Outro",
      "status": "Concluido",
      "reportedAt": "2026-04-01",
      "workshopEntryAt": null,
      "expectedExitAt": null,
      "workshopType": "",
      "workshop": "",
      "driver": "",
      "cost": null,
      "description": "Fuga na “ar pelo botão” (aguarda material)",
      "lastNote": "Carro está operacional",
      "lastNoteAt": "2026-04-02",
      "historyNotes": "2026-04-01: Fuga na “ar pelo botão” (aguarda material)\n 2026-04-02: [Concluido] Carro está operacional"
    },
    {
      "id": "AV0104191021",
      "equipment": 855,
      "plate": "LE-3158",
      "type": "Pneus",
      "status": "Concluido",
      "reportedAt": "2026-04-01",
      "workshopEntryAt": null,
      "expectedExitAt": null,
      "workshopType": "",
      "workshop": "",
      "driver": "",
      "cost": null,
      "description": "Substituir pneus do último eixo",
      "lastNote": "Substituir pneus do último eixo",
      "lastNoteAt": "2026-04-01",
      "historyNotes": "2026-04-01: Substituir pneus do último eixo"
    },
    {
      "id": "AV0104191101",
      "equipment": 855,
      "plate": "LE-3158",
      "type": "Carroceria",
      "status": "Concluido",
      "reportedAt": "2026-04-01",
      "workshopEntryAt": null,
      "expectedExitAt": null,
      "workshopType": "",
      "workshop": "",
      "driver": "",
      "cost": null,
      "description": "Reparar para-choques",
      "lastNote": "ok",
      "lastNoteAt": "2026-04-29",
      "historyNotes": "2026-04-01: Reparar para-choques\n2026-04-07: [Aguarda entrada na oficina] Fazer agendamento para Férias\n2026-04-29: [Concluido] ok"
    },
    {
      "id": "AV0104191245",
      "equipment": 841,
      "plate": "SE-1349",
      "type": "Carroceria",
      "status": "Concluido",
      "reportedAt": "2026-04-01",
      "workshopEntryAt": null,
      "expectedExitAt": null,
      "workshopType": "",
      "workshop": "",
      "driver": "",
      "cost": null,
      "description": "Para Choques partido",
      "lastNote": "ok",
      "lastNoteAt": "2026-04-29",
      "historyNotes": "2026-04-01: Para Choques partido\n2026-04-29: [Concluido] ok"
    },
    {
      "id": "AV0204092056",
      "equipment": 5296,
      "plate": "25-ZO-49",
      "type": "Outro",
      "status": "Concluido",
      "reportedAt": "2026-04-02",
      "workshopEntryAt": null,
      "expectedExitAt": "2026-04-02",
      "workshopType": "Interna",
      "workshop": "",
      "driver": "",
      "cost": null,
      "description": "Redução de potência\n Problema na bóia do Adblue",
      "lastNote": "ok para trabalhar",
      "lastNoteAt": "2026-04-02",
      "historyNotes": "2026-04-02: Redução de potência\n Problema na bóia do Adblue\n 2026-04-02: [Concluido] ok para trabalhar"
    },
    {
      "id": "AV0604160424",
      "equipment": 859,
      "plate": "75-ZS-77",
      "type": "Outro",
      "status": "Concluido",
      "reportedAt": "2026-04-06",
      "workshopEntryAt": null,
      "expectedExitAt": "2070-01-01",
      "workshopType": "Interna",
      "workshop": "Revisão",
      "driver": "",
      "cost": null,
      "description": "",
      "lastNote": "ok",
      "lastNoteAt": "2026-04-14",
      "historyNotes": "2026-04-06: Avaria registada\n2026-04-07: [Agendado] revisão a efetuar na oficina tojal\n2026-04-14: [Concluido] ok"
    },
    {
      "id": "AV0604160930",
      "equipment": 896,
      "plate": "L-198571",
      "type": "Carroceria",
      "status": "Parado",
      "reportedAt": "2026-04-01",
      "workshopEntryAt": "2026-04-07",
      "expectedExitAt": null,
      "workshopType": "Externa",
      "workshop": "Movimola",
      "driver": "",
      "cost": null,
      "description": "",
      "lastNote": ".",
      "lastNoteAt": "2026-04-15",
      "historyNotes": "2026-04-06: Avaria registada\n2026-04-07: [Agendado] Tribos partidos\n2026-04-15: [Aguarda pecas] .\n2026-04-15: [Parado] ."
    },
    {
      "id": "AV0604161111",
      "equipment": 5378,
      "plate": "BE08MB",
      "type": "Outro",
      "status": "Concluido",
      "reportedAt": "2026-04-02",
      "workshopEntryAt": null,
      "expectedExitAt": null,
      "workshopType": "Interna",
      "workshop": "Tojal- Fossa",
      "driver": "",
      "cost": null,
      "description": "",
      "lastNote": "ok",
      "lastNoteAt": "2026-04-14",
      "historyNotes": "2026-04-06: Avaria registada\n2026-04-14: [Concluido] ok"
    },
    {
      "id": "AV0704093143",
      "equipment": 877,
      "plate": "L-137878",
      "type": "Outro",
      "status": "Pode circular",
      "reportedAt": "2026-04-07",
      "workshopEntryAt": null,
      "expectedExitAt": null,
      "workshopType": "Interna",
      "workshop": "",
      "driver": "",
      "cost": null,
      "description": "Verificar placas vermelhas e branco... colocar luzes nas mesmas.\nChão em madeira.\nPrender as patolas de forma a não deslizarem de um lado para o outro.\nLuzes laterais, frontais e traseiras.\nCorrentes para amarrar a carga e esticadores.\nBorrachas para colocar o cilindro em cima.\nBarrotes em madeira.\nColocar ficha para pirilampo e pirilampo.\nNivel do 1ª eixo não sobe\nFarolim de marcha atrás\n",
      "lastNote": "Pode circular mas falta ir à oficina (coisa rápida) - 28/ ou 29/04",
      "lastNoteAt": "2026-04-24",
      "historyNotes": "2026-04-07: Verificar placas vermelhas e branco... colocar luzes nas mesmas.\nChão em madeira.\nPrender as patolas de forma a não deslizarem de um lado para o outro.\nLuzes laterais, frontais e traseiras.\nCorrentes para amarrar a carga e esticadores.\nBorrachas para colocar o cilindro em cima.\nBarrotes em madeira.\nColocar ficha para pirilampo e pirilampo.\nNivel do 1ª eixo não sobe\nFarolim de marcha atrás\n\n2026-04-15: [Parado] A aguardar peças\n2026-04-15: [Aguarda pecas] .\n2026-04-20: [Parado] Muitas coisas que fazer ainda\n2026-04-24: [Pode circular] Pode circular mas falta ir à oficina (coisa rápida) - 28/ ou 29/04"
    },
    {
      "id": "AV1404170055",
      "equipment": 868,
      "plate": "AJ15MG",
      "type": "Outro",
      "status": "Concluido",
      "reportedAt": "2026-04-14",
      "workshopEntryAt": null,
      "expectedExitAt": null,
      "workshopType": "Externa",
      "workshop": "Tempanálise",
      "driver": "",
      "cost": null,
      "description": "Precisa de ir à Tempanálise - tacógrafo",
      "lastNote": "ok",
      "lastNoteAt": "2026-04-29",
      "historyNotes": "2026-04-14: Precisa de ir à Tempanálise - tacógrafo\n2026-04-21: [Aguarda entrada na oficina] Vários problemas - travagem\n2026-04-29: [Concluido] ok"
    },
    {
      "id": "AV1404170310",
      "equipment": 890,
      "plate": "AU01EM",
      "type": "Travoes",
      "status": "Aguarda entrada na oficina",
      "reportedAt": "2026-04-14",
      "workshopEntryAt": null,
      "expectedExitAt": null,
      "workshopType": "Interna",
      "workshop": "",
      "driver": "",
      "cost": null,
      "description": "",
      "lastNote": "Avaria registada",
      "lastNoteAt": "2026-04-14",
      "historyNotes": "2026-04-14: Avaria registada"
    },
    {
      "id": "AV1504092515",
      "equipment": 858,
      "plate": "75-ZS-76",
      "type": "Carroceria",
      "status": "Concluido",
      "reportedAt": "2026-04-15",
      "workshopEntryAt": null,
      "expectedExitAt": null,
      "workshopType": "Externa",
      "workshop": "Golpiauto",
      "driver": "",
      "cost": null,
      "description": "",
      "lastNote": "ok",
      "lastNoteAt": "2026-04-29",
      "historyNotes": "2026-04-15: Avaria registada\n2026-04-29: [Concluido] ok"
    },
    {
      "id": "AV1504104403",
      "equipment": 867,
      "plate": "AJ50GD",
      "type": "Outro",
      "status": "Concluido",
      "reportedAt": "2026-04-15",
      "workshopEntryAt": null,
      "expectedExitAt": null,
      "workshopType": "Externa",
      "workshop": "MAN Turquel",
      "driver": "",
      "cost": null,
      "description": "Aguardar orçamento do modulo da caixa de velocidades - está na MAN",
      "lastNote": "ok",
      "lastNoteAt": "2026-04-29",
      "historyNotes": "2026-04-15: Aguardar orçamento do modulo da caixa de velocidades - está na MAN\n2026-04-16: [Parado] Troca de emails com MAN - sem previsão\n2026-04-29: [Concluido] ok"
    },
    {
      "id": "AV1504110943",
      "equipment": 5196,
      "plate": "24-FA-87",
      "type": "Outro",
      "status": "Concluido",
      "reportedAt": "2026-04-15",
      "workshopEntryAt": null,
      "expectedExitAt": "2026-04-18",
      "workshopType": "",
      "workshop": "",
      "driver": "",
      "cost": null,
      "description": "Fica pronta até 6º feira",
      "lastNote": "ok",
      "lastNoteAt": "2026-04-28",
      "historyNotes": "2026-04-15: Fica pronta até 6º feira\n2026-04-15: [Parado] 6º feira previsão\n2026-04-16: [Parado] 2º feira provavelmente estará pronta para trabalhar\n2026-04-20: [Parado] 20/04 > começaram trabalhos\n2026-04-28: [Concluido] ok"
    },
    {
      "id": "AV1604092432",
      "equipment": 818,
      "plate": "L-174917",
      "type": "Pneus",
      "status": "Concluido",
      "reportedAt": "2026-04-16",
      "workshopEntryAt": null,
      "expectedExitAt": null,
      "workshopType": "Interna",
      "workshop": "",
      "driver": "",
      "cost": null,
      "description": "Perde estabilidade na roda da frente",
      "lastNote": "ok",
      "lastNoteAt": "2026-04-20",
      "historyNotes": "2026-04-16: Perde estabilidade na roda da frente\n2026-04-20: [Concluido] ok"
    },
    {
      "id": "AV1604092852",
      "equipment": 5258,
      "plate": "44-QI-50",
      "type": "Outro",
      "status": "Concluido",
      "reportedAt": "2026-04-16",
      "workshopEntryAt": null,
      "expectedExitAt": null,
      "workshopType": "Interna",
      "workshop": "",
      "driver": "",
      "cost": null,
      "description": "Desumidificador com avaria, sábado dia 18/07 vai mecânico a Alenquer",
      "lastNote": "Filtro de partículas - 2-3 dias \nPoderá entrar em redução de potência",
      "lastNoteAt": "2026-04-20",
      "historyNotes": "2026-04-16: Desumidificador com avaria, sábado dia 18/07 vai mecânico a Alenquer\n2026-04-20: [Concluido] Filtro de partículas - 2-3 dias \nPoderá entrar em redução de potência"
    },
    {
      "id": "AV1704094903",
      "equipment": 884,
      "plate": "AT08RJ",
      "type": "Outro",
      "status": "Agendado",
      "reportedAt": "2026-04-17",
      "workshopEntryAt": "2026-04-17",
      "expectedExitAt": null,
      "workshopType": "Externa",
      "workshop": "Cortubai",
      "driver": "",
      "cost": null,
      "description": "Problema na tomada dupla",
      "lastNote": "Problema na tomada dupla",
      "lastNoteAt": "2026-04-17",
      "historyNotes": "2026-04-17: Problema na tomada dupla"
    },
    {
      "id": "AV2104092504",
      "equipment": 5258,
      "plate": "44-QI-50",
      "type": "Outro",
      "status": "Concluido",
      "reportedAt": "2026-04-21",
      "workshopEntryAt": null,
      "expectedExitAt": null,
      "workshopType": "",
      "workshop": "",
      "driver": "",
      "cost": null,
      "description": "Filtro de particulas",
      "lastNote": "ok",
      "lastNoteAt": "2026-04-29",
      "historyNotes": "2026-04-21: Filtro de particulas\n2026-04-29: [Concluido] ok"
    },
    {
      "id": "AV2104100614",
      "equipment": 864,
      "plate": "AJ48BP",
      "type": "Outro",
      "status": "Concluido",
      "reportedAt": "2026-04-21",
      "workshopEntryAt": null,
      "expectedExitAt": null,
      "workshopType": "Externa",
      "workshop": "MAN ",
      "driver": "",
      "cost": null,
      "description": "está à espera da aprovação oficina",
      "lastNote": "ok",
      "lastNoteAt": "2026-04-29",
      "historyNotes": "2026-04-21: está à espera da aprovação oficina\n2026-04-29: [Concluido] ok"
    },
    {
      "id": "AV2104100935",
      "equipment": 845,
      "plate": "SE-2067",
      "type": "Outro",
      "status": "Concluido",
      "reportedAt": "2026-04-21",
      "workshopEntryAt": null,
      "expectedExitAt": "2026-04-23",
      "workshopType": "",
      "workshop": "",
      "driver": "",
      "cost": null,
      "description": "Substituir discos + cubos ",
      "lastNote": "Ok",
      "lastNoteAt": "2026-04-23",
      "historyNotes": "2026-04-21: Substituir discos + cubos \n2026-04-23: [Concluido] Ok"
    },
    {
      "id": "AV2304110956",
      "equipment": 5270,
      "plate": "AV-55672",
      "type": "Outro",
      "status": "Concluido",
      "reportedAt": "2026-04-23",
      "workshopEntryAt": "2026-04-23",
      "expectedExitAt": "2026-04-27",
      "workshopType": "",
      "workshop": "",
      "driver": "",
      "cost": null,
      "description": "Cubos de rodas bloqueados",
      "lastNote": "ok",
      "lastNoteAt": "2026-04-27",
      "historyNotes": "2026-04-23: Cubos de rodas bloqueados\n2026-04-24: [Parado] Falta ir ao Unimolas - cubos resolvido\n2026-04-27: [Concluido] ok"
    },
    {
      "id": "AV2304111135",
      "equipment": 40146,
      "plate": "L-219999",
      "type": "Outro",
      "status": "Aguarda entrada na oficina",
      "reportedAt": "2026-04-22",
      "workshopEntryAt": null,
      "expectedExitAt": null,
      "workshopType": "Interna",
      "workshop": "EQ's fixos",
      "driver": "",
      "cost": null,
      "description": "",
      "lastNote": "Avaria registada",
      "lastNoteAt": "2026-04-23",
      "historyNotes": "2026-04-23: Avaria registada"
    },
    {
      "id": "AV2804100045",
      "equipment": 5194,
      "plate": "24-FA-85",
      "type": "Eletrica",
      "status": "Pode circular",
      "reportedAt": "2026-04-28",
      "workshopEntryAt": null,
      "expectedExitAt": null,
      "workshopType": "",
      "workshop": "",
      "driver": "",
      "cost": null,
      "description": "Não tem piscas, nem luzes. PLaca Alvará",
      "lastNote": "Não tem piscas, nem luzes. PLaca Alvará",
      "lastNoteAt": "2026-04-28",
      "historyNotes": "2026-04-28: Não tem piscas, nem luzes. PLaca Alvará"
    },
    {
      "id": "AV0505094531",
      "equipment": 858,
      "plate": "75-ZS-76",
      "type": "Outro",
      "status": "Parado",
      "reportedAt": "2026-05-05",
      "workshopEntryAt": null,
      "expectedExitAt": null,
      "workshopType": "Interna",
      "workshop": "",
      "driver": "",
      "cost": null,
      "description": "Problemas no comando do motor + para-choques",
      "lastNote": "Problemas no comando do motor + para-choques",
      "lastNoteAt": "2026-05-05",
      "historyNotes": "2026-05-05: Problemas no comando do motor + para-choques"
    },
    {
      "id": "AV0505094703",
      "equipment": 5205,
      "plate": "42-FF-74",
      "type": "Outro",
      "status": "Parado",
      "reportedAt": "2026-05-05",
      "workshopEntryAt": null,
      "expectedExitAt": null,
      "workshopType": "Externa",
      "workshop": "MAN Turquel",
      "driver": "",
      "cost": null,
      "description": "Caixa de velocidades a reparar",
      "lastNote": "Caixa de velocidades a reparar",
      "lastNoteAt": "2026-05-05",
      "historyNotes": "2026-05-05: Caixa de velocidades a reparar"
    },
    {
      "id": "AV0505094829",
      "equipment": 5298,
      "plate": "25-ZO-42",
      "type": "Outro",
      "status": "Aguarda entrada na oficina",
      "reportedAt": "2026-05-05",
      "workshopEntryAt": null,
      "expectedExitAt": null,
      "workshopType": "Externa",
      "workshop": "Golpiauto",
      "driver": "",
      "cost": null,
      "description": "Serviço de bate chapas ",
      "lastNote": "Serviço de bate chapas ",
      "lastNoteAt": "2026-05-05",
      "historyNotes": "2026-05-05: Serviço de bate chapas "
    },
    {
      "id": "AV0805095615",
      "equipment": 5337,
      "plate": "L-210305",
      "type": "Outro",
      "status": "Aguarda entrada na oficina",
      "reportedAt": "2026-05-08",
      "workshopEntryAt": null,
      "expectedExitAt": null,
      "workshopType": "Interna",
      "workshop": "",
      "driver": "",
      "cost": null,
      "description": "Fissuras na caixa junto ao cavalete\nEixo do meio não levanta em vazio\nFuga na caixa frente esq",
      "lastNote": "Fissuras na caixa junto ao cavalete\nEixo do meio não levanta em vazio\nFuga na caixa frente esq",
      "lastNoteAt": "2026-05-08",
      "historyNotes": "2026-05-08: Fissuras na caixa junto ao cavalete\nEixo do meio não levanta em vazio\nFuga na caixa frente esq"
    }
  ],
  "snapshots": [
    {
      "date": "2026-04-02",
      "active": 16,
      "stopped": 8,
      "waitingWorkshop": 6,
      "canCirculate": 1,
      "overdue": 0,
      "meetingNote": ""
    },
    {
      "date": "2026-04-06",
      "active": 15,
      "stopped": 7,
      "waitingWorkshop": 6,
      "canCirculate": 1,
      "overdue": 0,
      "meetingNote": null
    },
    {
      "date": "2026-04-06",
      "active": 16,
      "stopped": 7,
      "waitingWorkshop": 7,
      "canCirculate": 1,
      "overdue": 0,
      "meetingNote": null
    },
    {
      "date": "2026-04-06",
      "active": 18,
      "stopped": 2,
      "waitingWorkshop": 7,
      "canCirculate": 3,
      "overdue": 0,
      "meetingNote": null
    },
    {
      "date": "2026-04-07",
      "active": 18,
      "stopped": 3,
      "waitingWorkshop": 4,
      "canCirculate": 4,
      "overdue": 0,
      "meetingNote": null
    },
    {
      "date": "2026-04-07",
      "active": 18,
      "stopped": 2,
      "waitingWorkshop": 5,
      "canCirculate": 4,
      "overdue": 0,
      "meetingNote": null
    },
    {
      "date": "2026-04-08",
      "active": 18,
      "stopped": 2,
      "waitingWorkshop": 5,
      "canCirculate": 4,
      "overdue": 0,
      "meetingNote": "46238.0"
    },
    {
      "date": "2026-04-14",
      "active": 12,
      "stopped": 1,
      "waitingWorkshop": 4,
      "canCirculate": 1,
      "overdue": 1,
      "meetingNote": null
    },
    {
      "date": "2026-04-15",
      "active": 15,
      "stopped": 5,
      "waitingWorkshop": 3,
      "canCirculate": 1,
      "overdue": 0,
      "meetingNote": null
    },
    {
      "date": "2026-04-16",
      "active": 17,
      "stopped": 6,
      "waitingWorkshop": 3,
      "canCirculate": 3,
      "overdue": 1,
      "meetingNote": null
    },
    {
      "date": "2026-04-17",
      "active": 18,
      "stopped": 6,
      "waitingWorkshop": 3,
      "canCirculate": 3,
      "overdue": 1,
      "meetingNote": null
    },
    {
      "date": "2026-04-20",
      "active": 15,
      "stopped": 6,
      "waitingWorkshop": 3,
      "canCirculate": 1,
      "overdue": 2,
      "meetingNote": null
    },
    {
      "date": "2026-04-21",
      "active": 18,
      "stopped": 7,
      "waitingWorkshop": 5,
      "canCirculate": 1,
      "overdue": 2,
      "meetingNote": null
    },
    {
      "date": "2026-04-22",
      "active": 18,
      "stopped": 7,
      "waitingWorkshop": 5,
      "canCirculate": 1,
      "overdue": 2,
      "meetingNote": null
    },
    {
      "date": "2026-04-23",
      "active": 19,
      "stopped": 8,
      "waitingWorkshop": 6,
      "canCirculate": 1,
      "overdue": 2,
      "meetingNote": null
    },
    {
      "date": "2026-04-24",
      "active": 19,
      "stopped": 7,
      "waitingWorkshop": 6,
      "canCirculate": 2,
      "overdue": 2,
      "meetingNote": null
    },
    {
      "date": "2026-04-27",
      "active": 18,
      "stopped": 6,
      "waitingWorkshop": 6,
      "canCirculate": 2,
      "overdue": 2,
      "meetingNote": null
    },
    {
      "date": "2026-04-28",
      "active": 18,
      "stopped": 5,
      "waitingWorkshop": 6,
      "canCirculate": 3,
      "overdue": 1,
      "meetingNote": null
    },
    {
      "date": "2026-04-29",
      "active": 7,
      "stopped": 2,
      "waitingWorkshop": 2,
      "canCirculate": 2,
      "overdue": 0,
      "meetingNote": null
    },
    {
      "date": "2026-05-06",
      "active": 10,
      "stopped": 4,
      "waitingWorkshop": 3,
      "canCirculate": 2,
      "overdue": 0,
      "meetingNote": null
    },
    {
      "date": "2026-05-07",
      "active": 10,
      "stopped": 4,
      "waitingWorkshop": 3,
      "canCirculate": 2,
      "overdue": 0,
      "meetingNote": null
    },
    {
      "date": "2026-05-08",
      "active": 11,
      "stopped": 4,
      "waitingWorkshop": 4,
      "canCirculate": 2,
      "overdue": 0,
      "meetingNote": null
    }
  ]
};
